### ISSUE TITLE
pip install watch_recognition/ isn't working

### ISSUE THREAD

**Issue by ErezBorenshtein** [akucia/analog-watch-recognition#4]
I have tried to install the package and it didn't work.
It gave me this error: ERROR: Invalid requirement: 'watch_recognition/'

**Comment by akucia** [comment]
It's been a while, maybe there was something wrong in the commands at that point in time:

Try running the makefile command `dev-install` which does the following:
`pip install -r dev-requirements.txt && pip install -e ./watch_recognition`
